import { Chapter, Content, DirectoryRequest, Highlight, NetworkRequest, PagedResult } from "@suwatte/daisuke";
import { CheerioElement, TachiParsedHttpSource } from "../tachiyomi";
import { CheerioAPI } from "cheerio";
import moment from "moment";
export declare abstract class TachiDaraTemplate extends TachiParsedHttpSource {
    supportsLatest: boolean;
    protected dateFormat: string;
    headers(): Record<string, string>;
    protected filterNonMangaItems: boolean;
    protected mangaEntrySelector(): string;
    protected fetchGenres: boolean;
    protected mangaSubString: string;
    protected useNewChapterEndpoint: boolean;
    protected oldChapterEndpointDisabled: boolean;
    protected popularMangaUrlSelector: string;
    popularMangaSelector(): string;
    popularMangaNextPageSelector: () => string;
    popularMangaRequest(page: number): NetworkRequest;
    popularMangaFromElement(element: CheerioElement): Highlight;
    latestUpdatesSelector: () => string;
    latestUpdatesFromElement(element: CheerioElement): Highlight;
    latestUpdatesRequest(page: number): NetworkRequest;
    latestUpdatesNextPageSelector: () => string;
    parseLatestManga(html: string): PagedResult;
    searchMangaSelector(): string;
    searchMangaFromElement(element: CheerioElement): Highlight;
    searchMangaNextPageSelector(): string;
    searchMangaRequest(request: DirectoryRequest): NetworkRequest;
    mangaDetailsParse($: CheerioAPI): Content;
    chapterListSelector(): string;
    chapterDateSelector(): string;
    protected chapterUrlSelector: string;
    protected chapterUrlSuffix: string;
    oldXhrChaptersRequest(mangaId: string): NetworkRequest;
    xhrChaptersRequest(mangaUrl: string): NetworkRequest;
    parseDate(str: string): Date;
    parseRelativeDate(str: string): moment.Moment | null;
    getMangaChapters(id: string): Promise<Chapter[]>;
    chapterFromElement(element: CheerioElement): Omit<Chapter, "number" | "index" | "volume" | "language">;
    parseChapterList(_: string): Chapter[];
    pageListRequest(fragment: string): NetworkRequest;
    pageListParse($: CheerioAPI): string[];
    protected searchPage(page: number): string;
    protected imageFromElement(element: CheerioElement): string;
    protected mangaDetailsSelectorTitle: string;
    protected mangaDetailsSelectorAuthor: string;
    protected mangaDetailsSelectorArtist: string;
    protected mangaDetailsSelectorStatus: string;
    protected mangaDetailsSelectorDescription: string;
    protected mangaDetailsSelectorThumbnail: string;
    protected mangaDetailsSelectorGenre: string;
    protected mangaDetailsSelectorTag: string;
    protected seriesTypeSelector: string;
    protected altNameSelector: string;
    protected altName: string;
    protected pageListParseSelector: string;
    protected chapterProtectorSelector: string;
    protected notUpdating(val: string): void;
    protected completedStatusList: string[];
    protected ongoingStatusList: string[];
    protected hiatusStatusList: string[];
    protected canceledStatusList: string[];
}
