import { Chapter, ChapterData, Content, DirectoryFilter, DirectoryRequest, NetworkRequest, Option, PagedResult } from "@suwatte/daisuke";
import { TachiCatalogSource } from "./CatalogSource";
export declare abstract class TachiHttpSource extends TachiCatalogSource {
    abstract baseUrl: string;
    client: NetworkClient;
    constructor();
    headers(): Record<string, string>;
    abstract popularMangaRequest(page: number): NetworkRequest;
    abstract searchMangaRequest(request: DirectoryRequest): NetworkRequest;
    abstract latestUpdatesRequest(page: number): NetworkRequest;
    abstract parsePopularManga(response: string): PagedResult;
    abstract parseLatestManga(response: string): PagedResult;
    abstract parseMangaDetails(response: string): Content;
    abstract parseChapterList(response: string): Chapter[];
    abstract parsePageList(response: string): ChapterData;
    abstract parseSearchManga(response: string, context: DirectoryRequest): PagedResult;
    mangaDetailsRequest(fragment: string): NetworkRequest;
    chapterListRequest(fragment: string): NetworkRequest;
    pageListRequest(fragment: string): NetworkRequest;
    getPopularManga(page: number): Promise<PagedResult>;
    getLatestManga(page: number): Promise<PagedResult>;
    getSearchManga(searchRequest: DirectoryRequest): Promise<PagedResult>;
    getMangaDetails(id: string): Promise<Content>;
    getMangaChapters(id: string): Promise<Chapter[]>;
    getPageList(_: string, chapter: string): Promise<ChapterData>;
    imageRequest(url: string): Promise<NetworkRequest>;
    getFilterList(): Promise<DirectoryFilter[]>;
    getSortOptions(): Promise<Option[]>;
    getMangaURL(fragment: string): string;
}
