name: Publish

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - fix

jobs:
  publish-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: stt

  publish-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/fix'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages-test
          folder: stt